//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaP9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Telefono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telefono()
        {
            this.Total = new HashSet<Total>();
        }
    
        public int Idtelefono { get; set; }
        public string Marca { get; set; }
        public int Gama { get; set; }
        public int Ubicacion { get; set; }
        public int Color { get; set; }
        public Nullable<int> Precio { get; set; }

        //CAMPO FECHA
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy }", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Color Color1 { get; set; }
        public virtual Gama Gama1 { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total> Total { get; set; }
    }
}
